### ISSUE TITLE
The outer div container of the dialog is focusable

### ISSUE THREAD

**Issue by azhiv** [zestia/ember-modal-dialog#20]
I wonder why is the outer div of the dialog has `tab-index="0"`? Does it really have to be focusable? This causes an undesired frame render:
<img width="795" alt="Screenshot 2021-10-25 at 15 58 32" src="https://user-images.githubusercontent.com/32125472/161055222-fe6647ce-a89f-4f8d-962a-81fbf7e5c442.png">

**Comment by amk221** [comment]
If you have a modal with no inputs, and you click a button to open that modal, focus remains on that button (i.e. beneath the modal) - that's why we move focus to the modal.

You can remove the outline with CSS, or focus one of the form elements?

I have experimented with using `inert` on the contents beneath the modal but it raises some other issues.

**Comment by azhiv** [comment]
The thing is we don't want to focus anything automatically because it may cause undesired side effects. For example, focusing an element executes underlying logic or brings other element into view.
You could just blur the currently focused DOM element before showing the modal. Will that work?

**Comment by amk221** [comment]
I've been taking a look at native `dialog`, which this addon will move to eventually.
That is not focusable, so I've released 4.1.4.
But that said, MDN does say you should at least move focus to inside the modal still.
