### ISSUE TITLE
Pressing tab from the URL will not focus on the first element in the dialog

### ISSUE THREAD

**Issue by onin-baylen** [zestia/ember-modal-dialog#7]
While you have a dialog open, if you click on the URL bar and try to tab from it, it will not go to the first focusable element in your dialog.

Using as your demo as a sample (https://zestia.github.io/ember-modal-dialog/) from the URL textbox, when I click on tab, it will go to the "Fork me on Github" even when the dialog is open.

**Comment by amk221** [comment]
Hi 👋 

What OS and what browser are you using?

For me, if I am in the URL bar, and I press tab, focus moves to the buttons in my toolbar, and, if I keep tabbing, eventually it will focus the document. 

I suppose it could be expected that the _modal dialog_ would be focused, but I wouldn't expect it to go to the first focusable element in the dialog. Because that is the choice of the developer, not the addon. (For example, the addon does not attempt to focus any elements for you when opened).

Have you seen this desired behaviour elsewhere?

**Comment by onin-baylen** [comment]
I'm using Windows 10 and a Google Chrome Browser.

I'm not using a mouse here (except on clicking the address bar), then I just press tab. As you can see, the checkbox has been focused. Of course if the focus arrives on an item in the dialog, it will trap the focus on the elements in the dialog afterwards.

![image](https://user-images.githubusercontent.com/90294875/132475160-4571629c-685f-44b2-a891-2bc29b6b27b6.png)

**Comment by onin-baylen** [comment]
If this is something that is expected. Or something that the developer has to implement, then I will close this one.

**Comment by amk221** [comment]
Ok, it seems to be a Windows thing. I'll see what I can do...

**Comment by amk221** [comment]
Hi, can you please test `3.1.0-beta.0`

**Comment by onin-baylen** [comment]
Seems to be working, although it takes two tabs to get to the the first focusable item in the dialog. So I don't know where the focus is after pressing the first tab. But once you hit tab again its focus is moved to the first focusable item in my dialog.

**Comment by amk221** [comment]
Yeh, that seems right to me.

See the demo site - when you press tab, the modal dialog is focused.

Again:
> I suppose it could be expected that the modal dialog would be focused, but I wouldn't expect it to go to the first focusable element in the dialog. Because that is the choice of the developer, not the addon

**Comment by amk221** [comment]
I've had a change of heart about this. Think you're right.

**Comment by amk221** [comment]
I've had a change of heart on this, I think you're right
